### ISSUE TITLE
Creating the XML annotation files for RAVEN-FAIR

### ISSUE THREAD

**Issue by sshkhr** [yanivbenny/RAVEN_FAIR#1]
Is there a way to get the XML annotations that come with the original RAVEN code as well? The main.py file in the original code had it after saving the npz file (https://github.com/WellyZhang/RAVEN/blob/master/src/dataset/main.py#L281) but the RAVEN-FAIR code is missing this part: 

```python
 with open("{}/{}/RAVEN_{}_{}.xml".format(args.save_dir, key, k, set_name), "w") as f:
                dom = dom_problem(context + candidates, rule_groups)
                f.write(dom)
```

When I try to reuse their code with your repository I get a type mismatch error (context is a list, candidates is a tuple). After type conversion of candidates from tuple to list when I again run the code I got a shape mismatch error. 

Could you please implement the code to save XML annotations or explain why this issue arises?

**Comment by yanivbenny** [comment]
Hi
Following your request. We have downgraded the code to python 2.7.
The XML is now generated along with the dataset.

**Comment by sshkhr** [comment]
Wow, thank you so much for your consideration! That's extremely nice of you. 

Thanks again for finding the mode counting issue in the candidate images with RAVEN and addressing it.
